// Generated by CoffeeScript 1.7.1
(function() {
  var Tail, f, folder, fs, tail;

  fs = require('fs');

  Tail = require('./tail-watcher').TailWatcher;

  tail = new Tail('../../log/mylog.log');

  folder = require('./tail-watcher').FolderWatcher;

  f = new folder('../../log/');

  f.on('push', console.log);

}).call(this);
